### Practice Problem on Numpy

###### Problem-1 : NumPy 2D array
Problem Statement:  
GIven a 2D list, create a numpy 2D array using it.  
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  
Print the Numpy array.  

In [1]:
import numpy as np
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list_2d)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### Problem-2 : NumPy 0s and 1s
Problem Statement:  
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.

In [3]:
import numpy as np
arr = np.zeros(10, dtype=int)
arr[4] = 1
print(*arr)

0 0 0 0 1 0 0 0 0 0


###### Problem-3 : NumPy Inclusive
Problem Statement:  
Create an array with values ranging consecutively from 9 to 49 (both inclusive).  
Print the Numpy array.

In [4]:
import numpy as np
arr = np.arange(9,50)
print(*arr)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


###### Problem-4 : Identity Matrix
Problem Statement:  
Create an integer identity matrix of size (5, 6).  
Print the Numpy array.

In [5]:
import numpy as np
arr = np.eye(5,6,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


###### Problem-5 : Cut the Rope
Problem Statement:  
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.  
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.  
Print the array element.

In [8]:
import numpy as np
arr = np.linspace(0,5,10)
print(*arr)
for i in range(1, len(arr)-1) :
    print(round(arr[i],2))

0.0 0.5555555555555556 1.1111111111111112 1.6666666666666667 2.2222222222222223 2.7777777777777777 3.3333333333333335 3.8888888888888893 4.444444444444445 5.0
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


###### Problem-6 : Print Elements
Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

In [2]:
import numpy as np
input_ = np.arange(1,21,1)
input_ = input_.reshape(4,5)
print(*input_[2,:3])

print(*input_[1:4,3])

c = input_[2:4,:5]
print(*c[0],end=' ')
print(*c[1],end=' ')
print()

c = input_[1:3,1:3]
print(*c[0],end=' ')
print(*c[1],end=' ')


11 12 13
9 14 19
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

###### Problem-7 : Non-Zero elements
Problem Statemnt:  
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?  
Print the index of non-zero elements.


In [4]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
print(*ind[0])

0 1 4


###### Problem-8 : Multiples of 3
Problem Statement:  
Given an integer array of size 10. Print the index of elements which are multiple of 3.  
Note: Generate the following array
array([1,3,  5,  7,  9, 11, 13, 15, 17, 19])  
Print the index of elements.

In [5]:
import numpy as np
arr = np.arange(1,20,2)
ind = np.where(arr%3 == 0)
print(*ind[0])

1 4 7


###### Problem-9 : Odd elements
Problem Statemnt:  
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?  
Note: Generate the following array  
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  
Print the Numpy array.

In [7]:
import numpy as np
arr = np.arange(1,11)
arr[arr % 2 != 0] = -1
print(*arr)

-1 2 -1 4 -1 6 -1 8 -1 10


###### Problem-10 : Replace Max
Problem Statemnt:   
Given an integer array of size 10 and replace the first occurrence of maximum value by 0?   
Note: Generate the following array  
array([11, 2, 13, 4, 15, 6, 27, 8, 19])  
Print the Numpy array.

In [8]:
import numpy as np
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[arr.argmax()] = 0
for i in arr :
    print(i)

11
2
13
4
15
6
0
8
19


###### Problem-11 : Negate Elements
Problem Statemnt:  
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?  
Note: Generate the following array  
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  
Print the Numpy array.

In [9]:
import numpy as np
arr = np.arange(1,11)
arr[2:8] = np.multiply(arr[2:8],-1)
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


###### Problem-12 : Height
Problem Statemnt:  
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.  

In [11]:
import numpy as np
age = np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height = np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
index = np.where(height>155)
for i in range(len(index[0])) :
    print(age[index[0][i]],height[index[0][i]])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


###### Problem-13 : Sort by column
Problem Statemnt:  
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.  
That means, we should re-arrange complete row based on 2nd columns' values.  
Given 2D array is:  
 [[21 20 19 18 17]  
  [16 15 14 13 12]  
  [11 10  9  8  7]  
  [ 6  5  4  3  2]]  
Print the 2D array in sorted order.  
Note you have to generate the 2D Array.Here 2nd column means column present at index 1

In [12]:
import numpy as np
arr = np.arange(21,1,-1)
arr = arr.reshape(4,5)
print(arr[::-1])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

###### Problem-14 : Killed in USA
Problem Statement :  
Find value of killed column only where country == ‘United States’?  
Print 0 in place of missing values.  
Print count of Killed as integer value  

In [30]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed == ''] = '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country=="United States"
    ans = np_killed[bool_arr]
    print(ans)
    #for i in ans:
    #    print(int(i))

[0. 0. 0. ... 0. 0. 1.]


###### Problem-15 :  Total Killed in USA
Problem Statement :  
Find total number of people killed from USA?  
Note: Some columns of killed are empty so replace them by 0.  
Print count of Killed as integer value.

In [14]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed=='']= '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country == "United States"
    ans = np_killed[bool_arr]
    
    print(int(np.sum(ans)))

3771


### Assignment 

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

###### Problem-1 : Terrorism Day
Problem Statement :  
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)  
Print count of NumberOFAttack as integer value. 

In [17]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    days = []
    for row in data:
        days.append(row['Day'])
        
    np_days = np.array(days, dtype=float)
    ans = np_days[(np_days>=10) & (np_days<=20)]
    print(len(ans))


66330


###### Problem-2 : Terrorism Date
Problem Statement :  
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).  
Note Ignore the case where day is 0   
Print count of NumberOFAttack as integer value.  

In [19]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    days = []
    months = []
    year = []
    for row in data:
        days.append(row['Day'])
        months.append(row['Month'])
        year.append(row['Year'])
        
    np_day = np.array(days, dtype=float)
    np_month = np.array(months, dtype=float)
    np_year = np.array(year, dtype=float)
    
    np_day = np_day[np_month==1]
    np_year = np_year[np_month==1]
    np_day = np_day[np_year==2010]
    
    print(len(np_day[np_day!=0]))

271


###### Problem-3 :Terror Casualty Attack
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.  
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.  
Print the count of casualties (as integer), city in which that attack happened and name of attack group.  
Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0  

In [20]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    city = []
    casualty = []
    for row in data:
        if row["State"] == "Jammu and Kashmir" and row["Year"] == "1999" :
            if row["Month"] =="5" or row["Month"] == "6" or row["Month"] == "7" :
                casualty.append([row["Killed"],row["Wounded"]])
                city.append([row["City"],row['Group']])
                
    np_city = np.array(city)
    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    
    np_casualty = np.sum(np_casualty, axis=1)
    index = np.argmax(np_casualty)
    print(int(np_casualty[index]),np_city[index][0],np_city[index][1])

22 Kargil District Separatists


###### Problem-4 : Terror Casualty Red
Problem Statement :  
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.  
Note: Casualty=Killed +Wounded  
Print count of Casualty as integer value.  

In [22]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    casualty = []
    for row in data:
        if row['State']=='Chhattisgarh' or row['State']=='Odisha' or row['State']=='Jharkhand' or row['State']=='Andhra Pradesh':
                casualty.append([row["Killed"],row["Wounded"]])

    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    
    np_casualty = np.sum(np_casualty, axis=1)
    total_casualty = np.sum(np_casualty)
    print(int(total_casualty))

5628


###### Problem-5 : Terror City Casualty
Problem Statement :  
Find top 5 Indian Cities which has most number of casualties ?  
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.  
Note: Ignoring the City which is Unknown.  
Casualty = Killed + Wounded.

In [27]:
import numpy as np
import csv
from collections import Counter

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    city = []
    casualty = []
    for row in data:
         if row["Country"] == 'India' and row['City'] != 'Unknown':
                casualty.append([row["Killed"],row["Wounded"]])
                city.append(row["City"])
                
    np_city = np.array(city)
    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    np_casualty = np.sum(np_casualty, axis=1)
    
    dic = {}
    for i in range(len(np_city)):
        if np_city[i] in dic:
            dic[np_city[i]] += np_casualty[i]
        else:
            dic[np_city[i]] = np_casualty[i]

    k = Counter(dic) 
    high = k.most_common(5) 
    for i in high: 
        print(i[0],int(i[1])) 
        
    
    

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


###### Problem-6 : Terrorism FrequentDay
Problem Statement :  
Find the most frequent day of attack in a terrorismDataset ?
Note: Here np.unique can be used.  
Print count of frequent day and number of attack as Integer value.

In [29]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    day = []
    for row in data:
        day.append(row['Day'])
        
    np_day = np.array(day, dtype='int')
    day, count = np.unique(np_day, return_counts=True)
    index = np.argmax(count)
    print(day[index], count[index])

15 6500
